# Generated by Django 5.0.4 on 2024-04-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('published_at', models.DateTimeField()),
                ('thumbnail_url', models.URLField(max_length=2048)),
            ],
            options={
                'indexes': [models.Index(fields=['title'], name='syncthing_v_title_f759e4_idx'), models.Index(fields=['published_at'], name='syncthing_v_publish_53c646_idx')],
            },
        ),
    ]
