# Generated by Django 5.0.4 on 2024-04-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncthing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='video',
            name='syncthing_v_publish_53c646_idx',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='published_at',
            new_name='publishing_datetime',
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['publishing_datetime'], name='syncthing_v_publish_989677_idx'),
        ),
    ]
