# Generated by Django 5.0.4 on 2024-04-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncthing', '0002_remove_video_syncthing_v_publish_53c646_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='publishing_datetime',
            field=models.TextField(),
        ),
    ]
