# Generated by Django 5.0.4 on 2024-04-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncthing', '0004_video_video_id_alter_video_publishing_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
    ]
